### ISSUE TITLE
RFC: Components to remove in version 2

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-prototype-components#101]
As originally proposed, components that are added to GOV.UK Frontend should be removed from this project in a breaking release.

## Summary card

An upcoming version of GOV.UK Frontend will provide a [card variant for the existing summary list component](https://github.com/alphagov/govuk-frontend/pull/2931). This means the ‘Summary Card’ component is no longer required, or recommended. It should be removed in version 2.

## Task list

While the task list component has not been added to GOV.UK Frontend, the version being worked on for inclusion is now [available as a plugin component](https://github.com/x-govuk/task-list-component).

Should the component in this project, which follows the older but familiar and existing design be retained until an officially agreed upon component is added to GOV.UK Frontend. Or should authors be encouraged to use the new version being worked on instead?

## Deprecation

In the release for v1.1, we can include a deprecation notice for the affected component(s). Is a message in the release notes is enough?

Should a v1.x branch be maintained? Am thinking not (not sure what would change, and we should encourage authors to use official components from GOV.UK Frontend)

**Comment by frankieroberto** [comment]
Agree with removing task list and summary card. The expectation is that the task list gets merged into govuk-frontend this quarter (subject to an accessibility audit that GDS are running).
