### ISSUE TITLE
How do you set a selected value on the autocomplete component?

### ISSUE THREAD

**Issue by adamsilver** [x-govuk/govuk-prototype-components#143]
I tried to do this:

![Screenshot 2023-09-26 at 18 25 15@2x](https://github.com/x-govuk/govuk-prototype-components/assets/37163/309fde31-cf03-4061-8745-621e56340f97)

But it doesn’t work. 

From reading the docs, i have to have if statements against every item to then set selected to true.

Can you help me out please @paulrobertlloyd? 🙏

Without using xGovukAutocomplete (and manually install the autocomplete component files) I just set the `value` property of the select box to be `data.new.country` and it all hooked up.

**Comment by paulrobertlloyd** [comment]
Doesn’t look like `value` is being passed to `govukSelect` in the component; will fix and see if this then works.

**Comment by paulrobertlloyd** [comment]
Fixed and published in [2.0.3](https://github.com/x-govuk/govuk-prototype-components/releases/tag/v2.0.3) (:wave:, say hello to Elon for me… 😏)
