### ISSUE TITLE
Add support for right-aligned items within primary navigation

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-prototype-components#160]
This has been used in a few services, as well as in the draft One Login service header.

**Comment by frankieroberto** [comment]
Register trainee teachers has "Organisation details" right-aligned:

![task-list-2](https://github.com/x-govuk/govuk-prototype-components/assets/30665/bfe700db-b1f6-406b-84ee-19c6ef3e2d3e)

**Comment by frankieroberto** [comment]
Apply for teacher training has "Sign out" right-aligned:

![after-2](https://github.com/x-govuk/govuk-prototype-components/assets/30665/b12db535-7eac-44da-ba76-f25cdebae91b)

**Comment by paulrobertlloyd** [comment]
Given we’re deprecating this component, this issue is no longer relevant.
