### ISSUE TITLE
Suggestion for primary navigation component

### ISSUE THREAD

**Issue by adamsilver** [x-govuk/govuk-prototype-components#161]
The component `margin-top: -1px` when it comes after the phase banner.

I remove the border bottom from the phase banner when including primary navigation directly under it so the negative margin style is unnecessary/wrong.

I don’t think the primary nav component should be this opinionated (and interact with stuff outside of it).

What do you reckon?

**Comment by frankieroberto** [comment]
I’ve also removed the border from the bottom of the phase banner. I didn't spot the negative margin on the primary nav though, as I had to wrap the phase banner in a `<div class="govuk-width-container"></div>`, so the negative margin didn't apply.

I’d be happy to remove the negative margin, but perhaps @paulrobertlloyd can remember why it was originally added?

**Comment by paulrobertlloyd** [comment]
Opinionated maybe (though that opinion is fairly well scoped, only applying when the primary navigation directly follows a phase banner), but this does mean that there is not an odd clash of borders when using components together ‘out of the box’. If an author is customising  components, then they are on their own separate path already.

The alternative would be to provide documentation recommending removal of the bottom border on the phase banner, if used directly before this component. Are there any examples of this in the Design System? I wonder what approach they would take? I agree that one component shouldn’t create side effects on another, but what's the best way of avoiding the border clash?

**Comment by adamsilver** [comment]
Yeah, I would have guidance at most to get peeps to remove the border on the phase banner.

**Comment by frankieroberto** [comment]
Ah, I forgot the negative margin was to cover-up the border at the bottom of the phase banner!

**Comment by paulrobertlloyd** [comment]
Fixed in #192.
