### ISSUE TITLE
Secondary navigation

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-prototype-components#182]
As well as primary navigation, some services have secondary navigation as second horizontal row of navigation options.

Here’s an example from Manage training for early career teachers:

<img width="1252" alt="Screenshot 2023-12-12 at 10 07 28" src="https://github.com/x-govuk/govuk-prototype-components/assets/30665/550ea380-e6cf-4c7c-89cc-30a1c649d9e9">

The style there is very similar to the primary navigation, except with no background colour, and the current item has black text and a blue border at the bottom. It's placed after an h1 which is the scope for the secondary nav, and then the current item is repeated as an h2 after (possibly this isn't needed). 

Arguably this is similar to the [Tabs component](https://design-system.service.gov.uk/components/tabs/), but using links and full pages instead of javascript.

Worth considering adding as a prototype component?

**Comment by frankieroberto** [comment]
The MOJ Design System has a similar component, although there it’s called "[sub navigation](https://x-govuk.github.io/govuk-prototype-components/sub-navigation/)" - and they also have a "side navigation" (which here we’ve called sub navigation).

<img width="857" alt="Screenshot 2023-12-12 at 10 44 14" src="https://github.com/x-govuk/govuk-prototype-components/assets/30665/a3923806-148a-46ed-a920-eeedf6aced6c">

(Thanks @adamsilver for reminding me of this)

**Comment by paulrobertlloyd** [comment]
I think secondary navigation is a good name; want to add something we can include in v3.0? That’ll be a breaking change given the fixes to the Masthead component.

**Comment by frankieroberto** [comment]
Other examples from existing services:

* [Register trainee teachers](https://github.com/DFE-Digital/register-trainee-teachers-prototype/tree/52b96d2b2061f3907a08eadb251ff055b0007a8f/app/views/_components/sub-navigation) - thanks @edwardhorsford
* [Manage teacher training applications](https://github.com/DFE-Digital/manage-teacher-training-applications-prototype/tree/437bc5752dca93b5725f385846464248d1ec0367/app/views/_components/sub-navigation)
* [Teaching Vacancies](https://github.com/DFE-Digital/teaching-vacancies-prototype/tree/42c4c0d137ad85a2a663a2f1463049f2ab05dc4f/app/views/components/sub-navigation) - thanks @adamsilver
* [Publish teacher training courses](https://github.com/DFE-Digital/publish-teacher-training-prototype/tree/8d47fd7eaff65824292b72722f34834bb03b5247/app/views/_components/sub-navigation) – thanks @simonwhatley
* [Service assessment plus](https://github.com/DFE-Digital/book-manage-assure-services/blob/7b133731e7a859d6c714b58abb15fa72aa1114d4/app/views/admin/assessors/manage.html#L39-L54) - thanks Andy Jones
* [Complete conversions transfers and changes](https://github.com/DFE-Digital/complete-conversions-transfers-and-changes-prototype/blob/004848f26f0fc50e9b5ba3cfad0fe10f72434156/app/assets/sass/patterns/_sub-navigation.scss#L2)

plus [many more at DfE](https://github.com/search?q=org%3ADFE-Digital%20app-sub-navigation&type=code)...
