### ISSUE TITLE
Examples have a ‘Skip to main content’ link when they probably shouldn’t

### ISSUE THREAD

**Issue by edwardhorsford** [x-govuk/govuk-prototype-components#199]
If you tab through the example iFrames, you’ll come across ‘Skip to main content’ links. I suspect these are a mistake - they’re likely not relevant or helpful here.

![Screenshot 2023-12-19 at 21 03 16](https://github.com/x-govuk/govuk-prototype-components/assets/2204224/79ed9d83-9d5f-44f9-ac88-b11bc7a7f16a)

Note I compared to the design system site and it does not have these in this context.

**Comment by paulrobertlloyd** [comment]
Well spotted - more improvements to the docs to come!

**Comment by paulrobertlloyd** [comment]
Fixed in #201.

**Comment by edwardhorsford** [comment]
Nice one @paulrobertlloyd!
