### ISSUE TITLE
Package doesn’t work out of the box with prototype kit

### ISSUE THREAD

**Issue by fofr** [x-govuk/govuk-prototype-components#23]
When running the following instructions on a vanilla v12.1.0 prototype kit:

```sh
npm install govuk-prototype-components --save
```

And adding this to `app/assets/sass/application.scss:

```scss
@import "govuk-prototype-components/x-govuk/all";
```

You get this error:

```
app/assets/sass/unbranded.scss 16:9    root stylesheet
Error: Can't find stylesheet to import.
   ╷
22 │ @import "govuk-prototype-components/x-govuk/all";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

## Javascript

The instructions, if copied exactly lead to something like this in `application.js`:

```js
/* global $ */
const GOVUKPrototypeComponents = require('govuk-prototype-components')

// Warn about using the kit in production
if (window.console && window.console.info) {
  window.console.info('GOV.UK Prototype Kit - do not use for production')
}

$(document).ready(function () {
  window.GOVUKFrontend.initAll()
  window.GOVUKPrototypeComponents.initAll()
})
```

Nothing actually interprets the `require` and it gets passed straight through to the browser.

**Comment by paulrobertlloyd** [comment]
Hmmm, not so plug and play for the Prototype Kit, is it.

## Nunjucks macros

For Nunjucks macro import paths to be recognised, you need to add the following search location to Nunjucks path loader in `server.js`:

```diff
  // Set up App
  var appViews = extensions.getAppViews([
+   path.join(__dirname, '/node_modules/govuk-prototype-components'),
    path.join(__dirname, '/app/views/'),
    path.join(__dirname, '/lib/')
  ])
```

## SCSS

For the paths to SCSS files to be resolved, need to add `node_modules` to the gulp task in `gulp/sass.js`:

```diff
  gulp.task('sass', function () {
    return gulp.src(config.paths.assets + '/sass/*.scss', { sourcemaps: true })
      .pipe(sass.sync({
+       includePaths: 'node_modules',
        outputStyle: 'expanded',
        quietDeps: true
      }).on('error', function (error) {
    …
```

## JavaScript

This gets tricky (never simple with JavaScript) as the Prototype Kit doesn’t use a bundler, but imports scripts directly into the base layout via an include (`app/views/includes/scripts.html`).

Best option here might be to include a compiled version of the JavaScript required for all the components (which I think is just Edge and Autocomplete), and add documentation about copying this file into a folder and linking to it directly.

**Comment by paulrobertlloyd** [comment]
There is in 12.1.0 (download the ZIP), but removed in the repo for an upcoming release.

Wary of trying to fix/document any of this until we know how the new kit works.

**Comment by paulrobertlloyd** [comment]
Would have to update this line in the gulp-less version of the kit: https://github.com/alphagov/govuk-prototype-kit/blob/573c29e662906ea0a57162b47262104fee22d6db/lib/build/tasks.js#L67

**Comment by fofr** [comment]
The new kit without gulp has been released.
