### ISSUE TITLE
Fix link to sub-navigation

### ISSUE THREAD

**Issue by claire-hughez** [x-govuk/govuk-prototype-components#271]
On this [page for secondary navigation](https://x-govuk.github.io/govuk-prototype-components/secondary-navigation/), the link to the sub-navigation section is broken.

>Do not use this component for the primary sections of your service, or if a [sub-navigation](https://x-govuk.github.io/govuk-prototype-components/secondary-navigation/sub-navigation) would be more appropriate.

**Comment by claire-hughez** [comment]
@frankieroberto I tried to fix this but I had to fork it and... I don't know what forking is. Sorry! :D

**Comment by frankieroberto** [comment]
@claire-hughez thanks for reporting, this is fixed now! 😊

**Comment by claire-hughez** [comment]
Thanks, we used these for conversations about what the new ECF admin console will look like!
