### ISSUE TITLE
Allow `govukButton` to be decorated

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-prototype-components#4]
`button` elements can take `id`, `name` and `value` attributes, too.

**Comment by fofr** [comment]
Have you needed to do this?

**Comment by paulrobertlloyd** [comment]
Yup, shortly before I added this issue. I often use button values to change the status of a thing from draft to published, for example. Saves either creating a separate hidden input or updating the data in the POST route.
