### ISSUE TITLE
Guidance feedback

### ISSUE THREAD

**Issue by jesseyuen** [x-govuk/govuk-prototype-components#46]
Heya. Amazing work on this pals. 👏 

I'm working through the [Installation docs](https://x-govuk.github.io/govuk-prototype-components/#installation) and struggling! I have some feedback and a few questions.

**JavaScript** 

Do I need to add the javascript? 

What won't work if I don't add it?

It's not clear how to do either of these steps:

> - set up your routing so that requests for the JavaScript file are served from node_modules/govuk-prototype-components/x-govuk/all.js
> - copy the node_modules/govuk-prototype-components/x-govuk/all.js file into your application

Where is my routing set up and how do change where the files are served from?

Where exactly in my application do I copy the `all.js` file?

**Use the decorated form component macros**

Why am I replacing the Frontend macro imports with those provided by this package? It’s not clear what this gives me or what the benefit is.

> “Add the decorate global function to your Nunjucks environment”

Where is my Nunjucks environment?

**General feedback**

The below expert from the Nunjucks section is super useful.  Is it safe to we assume a lot of people installing these components will be using them in the kit and benefit from more specific guidance like this?  

![Screenshot 2022-07-15 at 08 17 54](https://user-images.githubusercontent.com/1108991/179172754-86576115-c01c-41cb-ae88-3a021e62c057.png)

Working though these docs and finding it tricky, I worry the docs are making too many assumptions about the designers understanding about what needs to go where and why.

**Comment by paulrobertlloyd** [comment]
@jesseyuen Closing this issue. v1.0.0 moves the decorated components to a separate project, and by using the Prototype Kit’a extension system, installation should be much more straight forward.
