### ISSUE TITLE
Proposal: Move decorated components to a separate project

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-prototype-components#57]
The decorated components are helpful, but have some downsides:

* It’s difficult to understand what these components are and why they’re beneficial (see @jesseyuen’s feedback in #46)
* In order to work with the GOV.UK Prototype Kit, they require digging into the weeds a bit to get working (and can’t be added easily using the Prototype Kit’s extension mechanism).
* They are bit of an ‘advanced’ feature

In addition, they conflict with the purpose of this project, which is to provide somewhat tested and definitive code for _new_ components that are widely used across government but not yet in the Design System.

## Proposal

* Create a new package (`govuk-decorated-components` perhaps), and move the decorated components (and [proposed decorated components](https://github.com/x-govuk/govuk-prototype-components/pull/49)) out of this package and into this new package, prior to the release of v1.0.0.
* Import this new package into the `govuk-prototype-rig` (which is fast becoming a means of collecting all these smaller packages into a greater whole)

**Comment by fofr** [comment]
👍 `govuk-decorated-components`

**Comment by fofr** [comment]
Obviously the decorated components would still be of great value in the kit, as well, if it's possible to make them available.

**Comment by paulrobertlloyd** [comment]
The README includes [instructions on how to add them to the GOV.UK Prototype Kit](https://github.com/x-govuk/govuk-decorated-components/blob/main/README.md).
